---

repo: 'ws-aws-app-deploy'
branch: 'prod'
description: 'Deploys HF1P958V4B to the prod'
uuid: '{{ rundeck_job_ids.prod["deploy_HF1P958V4B"] }}'
aws_env: 'prod'
playbook: 'lambda_deploy.yml'
playbook_inventory: 'aws_inventory.py'
playbook_vars:
  env: 'prod'
  product: 'service'
  app_name: 'HF1P958V4B'
  artifact_key: 'prod-HF1P958V4B'
# This needs the INVENTORY_ENV=prod for any migrations that are run
# as the migrations are run on the Docker Batch server (currently only in prod)
environment_variables:
  INVENTORY_ENV: 'prod'
